### ISSUE TITLE
Start server [Bug]: 

### ISSUE THREAD

**Issue by logistic94** [DexxKnight1/TechRevolution#3]
### General Info

- [x] I didn't added any mods
- [ ] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [x] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0.3

### Describe your issue

Cant start server, in pc install java 17 

```
2023-09-21 01:15:29,719 main WARN Advanced terminal features are not available in this environment
[01:15:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.23, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, nogui]
[01:15:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[01:15:31] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/F:/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
        at java.base/java.nio.file.Files.provider(Files.java:105)
        at java.base/java.nio.file.Files.isDirectory(Files.java:2316)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.23/net.minecraftforge.fml.loading.FileUtils.getOrCreateDirectory(FileUtils.java:24)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.23/net.minecraftforge.fml.loading.FMLPaths.loadAbsolutePaths(FMLPaths.java:62)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.23/net.minecraftforge.fml.loading.FMLPaths.setup(FMLPaths.java:52)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.23/net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:63)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:92)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:92)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:51)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Restarting automatically in 10 seconds (press Ctrl + C to cancel)
```

### Steps to reproduce the issue

startserver.bat
![image](https://github.com/DexxKnight1/TechRevolution/assets/22627391/d769ceb6-77c7-46ce-baa8-269be4b8dcc9)

### Additional Information

[21сент.2023 01:17:51.181] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.23, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, nogui]
[21сент.2023 01:17:51.185] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[21сент.2023 01:17:51.206] [main/DEBUG] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Found launch services [fmlclientdev,forgeclient,minecraft,forgegametestserverdev,fmlserveruserdev,fmlclient,fmldatauserdev,forgeserverdev,forgeserveruserdev,forgeclientdev,forgeclientuserdev,forgeserver,forgedatadev,fmlserver,fmlclientuserdev,fmlserverdev,forgedatauserdev,testharness,forgegametestserveruserdev]
[21сент.2023 01:17:51.224] [main/DEBUG] [cpw.mods.modlauncher.NameMappingServiceHandler/MODLAUNCHER]: Found naming services : [srgtomcp]
[21сент.2023 01:17:51.234] [main/DEBUG] [cpw.mods.modlauncher.LaunchPluginHandler/MODLAUNCHER]: Found launch plugins: [mixin,eventbus,slf4jfixer,object_holder_definalize,runtime_enum_extender,capability_token_subclass,accesstransformer,runtimedistcleaner]
[21сент.2023 01:17:51.240] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Discovering transformation services
[21сент.2023 01:17:52.650] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Found additional transformation services from discovery services: [F:\mods\JCPlugin-1.17.x-1.20.x-4.0.4-Forge.jar][F:\mods\serializationisbad-1.5.jar]
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Found transformer services : [jcplugin,mixin,fml,serializationisbad]
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Transformation services loading
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service jcplugin
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service jcplugin
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service mixin
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service mixin
[21сент.2023 01:17:52.661] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service fml
[21сент.2023 01:17:52.664] [main/DEBUG] [net.minecraftforge.fml.loading.LauncherVersion/CORE]: Found FMLLauncher version 1.0
[21сент.2023 01:17:52.664] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML 1.0 loading
[21сент.2023 01:17:52.664] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found ModLauncher version : 10.0.8+10.0.8+main.0ef7e830
[21сент.2023 01:17:52.664] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found AccessTransformer version : 8.0.4+66+master.c09db6d7
[21сент.2023 01:17:52.664] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found EventBus version : 6.0.3+6.0.3+master.039e4ea9
[21сент.2023 01:17:52.664] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Found Runtime Dist Cleaner
[21сент.2023 01:17:52.665] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: FML found CoreMod version : 5.0.1+15+master.dc5a2922
[21сент.2023 01:17:52.665] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Found ForgeSPI package implementation version 6.0.0+6.0.0+master.42474703
[21сент.2023 01:17:52.665] [main/DEBUG] [net.minecraftforge.fml.loading.FMLLoader/CORE]: Found ForgeSPI package specification 5
[21сент.2023 01:17:52.666] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service fml
[21сент.2023 01:17:52.666] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loading service serializationisbad
[21сент.2023 01:17:52.666] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Loaded service serializationisbad
[21сент.2023 01:17:52.667] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Configuring option handling for services
[21сент.2023 01:17:52.670] [main/DEBUG] [cpw.mods.modlauncher.TransformationServicesHandler/MODLAUNCHER]: Transformation services initializing
[21сент.2023 01:17:52.670] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initializing transformation service jcplugin
[21сент.2023 01:17:52.670] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initialized transformation service jcplugin
[21сент.2023 01:17:52.670] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initializing transformation service mixin
[21сент.2023 01:17:52.678] [main/DEBUG] [mixin/]: MixinService [ModLauncher] was successfully booted in cpw.mods.cl.ModuleClassLoader@7a30d1e6
[21сент.2023 01:17:52.687] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/F:/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[21сент.2023 01:17:52.689] [main/DEBUG] [mixin/]: Initialising Mixin Platform Manager
[21сент.2023 01:17:52.690] [main/DEBUG] [mixin/]: Adding mixin platform agents for container ModLauncher Root Container(ModLauncher:4f56a0a2)
[21сент.2023 01:17:52.690] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentMinecraftForge for ModLauncher Root Container(ModLauncher:4f56a0a2)
[21сент.2023 01:17:52.690] [main/DEBUG] [mixin/]: MixinPlatformAgentMinecraftForge rejected container ModLauncher Root Container(ModLauncher:4f56a0a2)
[21сент.2023 01:17:52.690] [main/DEBUG] [mixin/]: Instancing new MixinPlatformAgentDefault for ModLauncher Root Container(ModLauncher:4f56a0a2)
[21сент.2023 01:17:52.691] [main/DEBUG] [mixin/]: MixinPlatformAgentDefault accepted container ModLauncher Root Container(ModLauncher:4f56a0a2)
[21сент.2023 01:17:52.691] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initialized transformation service mixin
[21сент.2023 01:17:52.691] [main/DEBUG] [cpw.mods.modlauncher.TransformationServiceDecorator/MODLAUNCHER]: Initializing transformation service fml
[21сент.2023 01:17:52.691] [main/DEBUG] [net.minecraftforge.fml.loading.FMLServiceProvider/CORE]: Setting up basic FML game directories

**Comment by DexxKnight1** [comment]
For 1.19.2 server you need Java 17. In Server files you have description about how to run a localhost server. Please read before you post a issue.

[README-server guide.txt](https://github.com/DexxKnight1/TechRevolution/files/12682401/README-server.guide.txt)

Here is a [tutorial](https://www.youtube.com/watch?v=A5FHcR3cE-w) how to switch between Java versions.

**Comment by logistic94** [comment]
> For 1.19.2 server you need Java 17. In Server files you have description about how to run a localhost server. Please read before you post a issue.
> 
> [README-server guide.txt](https://github.com/DexxKnight1/TechRevolution/files/12682401/README-server.guide.txt)
> 
> Here is a [tutorial](https://www.youtube.com/watch?v=A5FHcR3cE-w) how to switch between Java versions.
i read tutorial, and i have 17 java 
![image](https://github.com/DexxKnight1/TechRevolution/assets/22627391/ba980fda-fa3f-456c-90fa-835f49b93cee)

**Comment by logistic94** [comment]
Have another problem
[13:23:04] [FTB Backups Config Watcher 0/INFO] [ne.cr.ft.FTBBackups/]: Config at C:\Users\avpno\Desktop\serv\config\ftbbackups2.json has changed, reloaded!
